on:
  workflow_dispatch:
  push:
    branches:
      - main
name: release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v2
        id: release-please
        with:
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: main
      # The logic below handles the npm publication:
      - name: Checkout
        uses: actions/checkout@v2
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
        if: ${{ steps.release.outputs.release_created }}

      - name: Install dependencies
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7
          run_install: true
        if: ${{ steps.release.outputs.release_created }}

      - name: Test
        run: pnpm run --if-present test:node
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        run: |
          pnpm -r publish --access=public
